#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

#  create the index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx start
sudo service nginx restart
