#!/usr/bin/env bash
# Installs HAProxy version 2.6 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
frontend abnb
    bind *:80
    mode http
    default_backend abnb_backend
backend abnb_backend
    balance roundrobin
    server 73323-web-01 100.25.205.58:80 check
    server 73323-web-02 100.25.215.159:80 check
    
" >> /etc/haproxy/haproxy.cfg

service haproxy start
